models/branch: Fix `route()` to return nil
Under certain circumstances, when accessing the menu *Baumstruktur* results in
the error below.

```
An ActionView::Template::Error occurred in branches#index:

  undefined method `name' for false:FalseClass
  app/views/branches/_branch.html.haml:12:in `_app_views_branches__branch_html_haml__4187413576081855020_70172628976900'
[…]
```

Fix up the typo introduced by commit f488302d (zwischenstand …) by
returning `nil`.

Note, the code will still throw an exception.